vich_uploader:
  db_driver: orm

  mappings:
    question_images:
      uri_prefix: '%app.path.question_images%'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      upload_destination: '%kernel.project_dir%/public%app.path.question_images%'
